#!/bin/sh

USER_STAMP=$HOME/.xdg-menu-updates.stamp
USER_MENU=$HOME/.local/

RETVAL=0

if [ -d $USER_MENU -o -f $USER_STAMP -a -f $SYSTEM_STAMP  ]; then
    if [ ! -f $USER_STAMP ]; then
            RETVAL=1;
    elif [ $SYSTEM_STAMP -nt $USER_STAMP ]; then
            RETVAL=1;
    fi
    if [ $RETVAL -eq 1 ]; then
        echo -n "Running update-menus..."
        update-menus -u
        echo done
    fi
fi


# menu ends here
