#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : sbin
# File            : fndSession
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Mon May 30 10:43:12 2005
# Purpose         : find sessions for display managers
#---------------------------------------------------------------

umask 022

FILES=`/bin/ls /usr/share/X11/dm.d/*.conf 2> /dev/null`

if [ $? != 0 ]; then
	exit 0
fi

for f in $FILES; do
    EXEC=
    FNDSESSION_EXEC=
    eval `grep 'EXEC=' "$f"`
    if [ -x "$EXEC" -a -n "$FNDSESSION_EXEC" ]; then
	$FNDSESSION_EXEC
    fi
done

# fndSession ends here
