.\" Written by Camille Bégnis 12/28/99
.TH CHKSESSION 8 "Dec 1999" "mandrake_desk" "MandrakeSoft"
.SH НАЗВА
chksession \- додає/прибирає сесії з менеджерів дисплеїв
.SH ВИКОРИСТАННЯ
.B chksession 
[\fIПАРАМЕТР\fR]...
.SH ОПИС
.PP
.PP
chksession надає можливість системному адміністратору керувати
списками сесій, які надаються обома менеджерами дисплеїв gdm і
kdm. Команда змінює відповідні файли конфіґурації щоб додати чи
прибрати сесії доступні для використання як  kde, gnome, icewm...
.TP
\fB\-F\fR, \fB\-\-first\fR
Друкує тільки перший пункт з конфіґураційного файла.
.TP
\fB\-f=FILE\fR, \fB\-\-file=ФАЙЛ\fR
Використовувати інший конфіґураційний файл, відмінний від  \fI/etc/X11/window-manager\fR
.TP
\fB\-g\fR, \fB\-\-gdm\fR
Поновити список віконних менеджерів для сесій gdm використовуючи або
стандартний конфіґураційний файл або ФАЙЛ вказаний параметром  \fB\-f\fR.
.TP
\fB\-h\fR, \fB\-\-help\fR
Друкує коротку підказку.
.TP
\fB\-k\fR, \fB\-\-kdm\fR
Поновити список віконних менеджерів для сесій kdm використовуючи або
стандартний конфіґураційний файл або ФАЙЛ вказаний параметром  \fB\-f\fR.
.TP
\fB\-l\fR, \fB\-\-list\fR
Перечислити віконні менеджер з конфіґураційного файла.
.TP
\fB\-r=ENTRY\fR, \fB\-\-remove=ПУНКТ\fR
Друкує на стандартний вивід список віконних менеджерів з
конфіґураційного файла, з яких прибрано ПУНКТ.
.TP
\fB\-t\fR, \fB\-\-test\fR
Перейти в режим тестування.
.TP
\fB\-x=ENTRY\fR, \fB\-\-xsession=ПУНКТ\fR
Друкує на стандартний вивід скрипт, який використовується для запуску
віконного менеджера, вказаного в ПУНКТ'і.
.SH "СТРУКТУРА КОНФІҐУРАЦІЙНОГО ФАЙЛА"
Цей файл описує кожен віконний менеджер, який буде доступний для
менеджерів дисплеїв. Кожен пункт в цьому файлі відділяється від інших
рядком  \fB\-\-@@\-\-\fR .
.PP
.B NAME=
назва сесії, яка показується в списку менеджера дисплеїв.
.PP
.B ICON=
файл піктограми (\fI.xpm чи .png\fR) яка використовується для цієї сесії.
.PP
.B DESC=
короткий опис сесії.
.PP
.B EXEC=
командний рядок для перевірки чи встановлений менеджер сесій чи ні.
.PP
.B SCRIPT:
командний скрипт для запуску вибраного користувачем віконного менеджера.
.SH ФАЙЛИ
.TP 
\fB\/etc/X11/window-manager\fR
стандартний конфіґураційний файл, містить список всіх найбільш відомих
віконних менеджерів. Це \-\- головний файл, який використовується
\fBchksessio\fRn для поновлення конфіґураційних файлів обох менеджерів
дисплеїв gdm і kdm.
.SH "ЗВІТИ ПРО ПОМИЛКИ"
Повідомляйте про помилки за адресою \fBhttp://www.linux-mandrake.com/bugs/\fR.
.SH "ДИВ. ТАКОЖ"
\fIxdm\fR(1)
.SH АВТОРСЬКІ ПРАВА
Copyright \(co 1999 MandrakeSoft.
.br
Це вільне програмне забезпечення на правах GPL. Зверніться до вихідних
текстів за інформацією про умови розповсюдження. НЕ надається
гарантії, навіть щодо можливості ПРОДАЖУ чи ПРИГОДНОСТІ певним цілям.

.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
