#!/bin/sh

usage() {
echo "Usage: update-menus [options]"
echo "  -v                     Be verbose about what is going on."
echo "  -u  generate only user menu (useful for root user)"
echo "  -h, --help             This message."

exit 0	
}


VERBOSE=0

if [ "$DURING_INSTALL" = "1" ]; then
  exit 0
fi

if [ "$UID" == "0" ]; then 
 USER_MENU=0 
else 
 USER_MENU=1
fi

if [ $# != 0 ]; then

while getopts ":vunh" option
do
  case $option in
    v     ) VERBOSE=1 ; RUN_PARTS_ARG="--verbose" ;;
    u     ) USER_MENU=1 ;;
    h     ) usage ;;
  esac
done
fi

export VERBOSE
export USER_MENU

if [ -d /etc/menu.d ]; then 
   run-parts $RUN_PARTS_ARG /etc/menu.d
   if [ "$USER_MENU" = "1" ]; then
	   touch "$HOME/.menu-updates.stamp" 2> /dev/null
   else 
	   touch /var/lib/menu/.menu-updates.stamp 2> /dev/null
   fi 
fi

